    <!-- Home Section Start -->
    <section class="home-section">
        <div class="container">
            <div class="row">
                
                 <div class="col-sm-offset-2 col-md-4 col-sm-6 margin-left-setting">
                    <div class="me-image">
					<img width='100' src="images/bg/khelafat-majlish-logo.png" alt=""> 
					</div>
                 </div>
                 
                 <div class="col-md-5 col-sm-6">
                    <div class="me-image">
						<img width='300' src="images/etc/mawlana_ishaq-khelafat-majlish.jpg" alt="">
						<img src="images/etc/khelafat-majlish-dr-ahmed-abdul-kader.jpg" alt="">
                  </div>
                </div>
              </div>
            </div>
        </section>
        <!-- Home Section End -->
        
        <?php $posts = $GLOBALS['api']->getPosts(array('rows' => 3)); ?>
        <?php $randPosts = $GLOBALS['api']->getPosts(array('rows' => 3, 'start' => 4, 'type' => 'random')); ?>
        
        
    <!-- Experience Start -->
    <section class="section-space-padding">
        <div class="container">
           <div class="row">
                <div class="col-sm-12">
                    <div class="section-title">
                        <h2>বিসমিল্লাহির রাহমানির রাহিম </h2>
                         <div class="divider dark">
						   <i class="icon-graduation"></i>
						  </div>
                        <p>মানুষ আল্লাহর খলিফা ও বান্দা । খেলাফত ও উবুদিয়্যাতের দায়িত্ব যথাযথভাবে আঞ্জাম দেয়ার উপরই মানুষের দুনিয়ার সামগ্রিক কল্যাণ এবং আখেরাতের মুক্তি ও শান্তি নির্ভরশীল। 

ইসলাম মানুষের জন্য মনোনীত দ্বীন ও সর্বোত্তম জীবন ব্যবস্থা। ইবলিসী চক্রান্তে সৃষ্ট শোষণ-নির্যাতন, নৈরাজ্য, অনৈক্য-বিভেদ, অন্যায়-অবিচার-অনাচার, যুদ্ধ-সংঘাতে পরিপূর্ণ বিপর্যস্ত পৃথিবীর হতাশাগ্রস্ত মানুষের একমাত্র মুক্তির পথ ইসলাম। সমাজের সর্বস্তরে ইসলামের পূর্ণ প্রতিষ্ঠাই শান্তি ও অগ্রগতি, সুবিচার ও সাম্যের নিশ্চয়তা দিতে পারে। 

বর্তমানে উলামা মাশায়েখ ও দ্বীনদার শ্রেণীর মাধ্যমে ইসলামের বিভিন্ন পরিমন্ডলে ইসলামের বাস্তবরূপ তথা খেলাফত ব্যবস্থা কায়েম নেই দীর্ঘদিন ধরে। অথচ মানবতার বিশেষভাবে মুসলিম বিশ্বের মুক্তি, সমৃদ্ধি, সম্মান ও দায়িত্ব গোটা মুসলিম জাতির, বিশেষভাবে উলামা-মাশায়েখ, দ্বীনদার বুদ্ধিজীবী ও রাজনীতিকদের।

বাংলাদেশের ক্ষেত্রে এ সত্য সমভাবে প্রযোজ্য। এখানকার সামাজিক বৈষম্য, অর্থনৈতিক শোষণ, রাজনৈতিক নিপীড়ন, হানাহানি, সাংস্কৃতিক নৈরাজ্য ও দেউলিয়াপনা এবং বৈদেশিক আধিপত্যের অবসানে গোটা সমাজ ব্যবস্থাকে ইসলামের আলোকে পুনর্গঠিত করতে হবে। দেশের পনের কোটি মানুষের কল্যাণ ও সমৃদ্ধির জন্য ইসলামী আদর্শের ভিত্তিতে সমাজের বিপ্লবাত্মক পরিবর্তন তথা একটি ইসলামী বিপ্লব প্রয়োজন। প্রয়োন খেলাফত ব্যবস্থাকে এখানে পুনরুজ্জীবিত করে দেশকে সত্যিকার অর্থে একটি সার্বজনীন কল্যাণ রাষ্ট্রে পরিণত করা। এ শুধু পার্থিব প্রয়োজনেই নয় বরং আখেরাতের মুক্তির জন্যো অপরিহার্য।

বাংলার জমীনে আল্লাহ্র খেলাফত প্রতিষ্ঠার লক্ষ্যে এ দেশের ইসলামী আন্দোলনের ক্ষেত্রে এক নবতর সমন্বয়ধর্মী ও গণভিত্তিক ঐতিহ্য-চেতনা সমৃদ্ধ আপোষহীন নির্ভেজাল ইসলামী আন্দোলন গড়ে তোলার প্রয়োজনে ১৯৮৯ সালের ৮ই ডিসেম্বর খেলাফত মজলিস আত্মপ্রকাশ করেছে।</p>
                    </div>
                </div>
            </div>
            
            <div class="row">
            
            <div class="col-md-12 col-sm-12">
				<div class="experience">
                <h3 class=''>Latest News</h3>
				
                <?php foreach($posts->getItems() as $post) { ?>
				<div class="experience-item">
					<div class="experience-circle">
					   <i class="icon-graduation"></i> 
                       <p><?php echo $post->getDate(); ?></p>
					</div>
					<div class="experience-content experience-color-blue">
						<h4><?php echo $post->getTitle(); ?></h4>
                        <h6><?php echo $post->getAuthorName(); ?></h6>
						<p><?php echo $post->getExcerpt(); ?> 
                        ... &ensp;<i><a href='<?=$post->getUrl();?>'>আরও পড়ুন</a></i>
                        </p>
					</div>
				 </div>
                 <?php } ?>
				
			 </div>
			</div>

			<div class="col-md-12 col-sm-12">
				<div class="experience">
                <h3 class=''>Latest News</h3>
				<?php foreach($randPosts->getItems() as $post) { ?>
				<div class="experience-item">
					<div class="experience-circle experience-company pink-color-bg">
					   <i class="icon-graduation"></i> 
                       <p><?php echo $post->getDate(); ?></p>
					</div>
					<div class="experience-content experience-color-blue">
						<h4><?php echo $post->getTitle(); ?></h4>
                        <h6><?php echo $post->getAuthorName(); ?></h6>
						<p><?php echo $post->getExcerpt(); ?> 
                        ... &ensp;<i><a href='<?=$post->getUrl();?>'>আরও পড়ুন</a></i>
                        </p>
					</div>
				 </div>
                 <?php } ?>
				
			 </div>
			</div>
            
           </div>
        </div>
    </section>
    <!-- Experience End -->
    
    
    <!-- About Start -->
    <section id="about" class="about section-space-padding">
       <div class="container">
          <div class="row">
                <div class="col-sm-12">
                    <div class="section-title">
                        <h2>বিসমিল্লাহির রাহমানির রাহিম </h2>
                         <div class="divider dark">
						   <i class="icon-emotsmile"></i>
						  </div>
                        <p>মানুষ আল্লাহর খলিফা ও বান্দা । খেলাফত ও উবুদিয়্যাতের দায়িত্ব যথাযথভাবে আঞ্জাম দেয়ার উপরই মানুষের দুনিয়ার সামগ্রিক কল্যাণ এবং আখেরাতের মুক্তি ও শান্তি নির্ভরশীল। 

ইসলাম মানুষের জন্য মনোনীত দ্বীন ও সর্বোত্তম জীবন ব্যবস্থা। ইবলিসী চক্রান্তে সৃষ্ট শোষণ-নির্যাতন, নৈরাজ্য, অনৈক্য-বিভেদ, অন্যায়-অবিচার-অনাচার, যুদ্ধ-সংঘাতে পরিপূর্ণ বিপর্যস্ত পৃথিবীর হতাশাগ্রস্ত মানুষের একমাত্র মুক্তির পথ ইসলাম। সমাজের সর্বস্তরে ইসলামের পূর্ণ প্রতিষ্ঠাই শান্তি ও অগ্রগতি, সুবিচার ও সাম্যের নিশ্চয়তা দিতে পারে। 

বর্তমানে উলামা মাশায়েখ ও দ্বীনদার শ্রেণীর মাধ্যমে ইসলামের বিভিন্ন পরিমন্ডলে ইসলামের বাস্তবরূপ তথা খেলাফত ব্যবস্থা কায়েম নেই দীর্ঘদিন ধরে। অথচ মানবতার বিশেষভাবে মুসলিম বিশ্বের মুক্তি, সমৃদ্ধি, সম্মান ও দায়িত্ব গোটা মুসলিম জাতির, বিশেষভাবে উলামা-মাশায়েখ, দ্বীনদার বুদ্ধিজীবী ও রাজনীতিকদের।

বাংলাদেশের ক্ষেত্রে এ সত্য সমভাবে প্রযোজ্য। এখানকার সামাজিক বৈষম্য, অর্থনৈতিক শোষণ, রাজনৈতিক নিপীড়ন, হানাহানি, সাংস্কৃতিক নৈরাজ্য ও দেউলিয়াপনা এবং বৈদেশিক আধিপত্যের অবসানে গোটা সমাজ ব্যবস্থাকে ইসলামের আলোকে পুনর্গঠিত করতে হবে। দেশের পনের কোটি মানুষের কল্যাণ ও সমৃদ্ধির জন্য ইসলামী আদর্শের ভিত্তিতে সমাজের বিপ্লবাত্মক পরিবর্তন তথা একটি ইসলামী বিপ্লব প্রয়োজন। প্রয়োন খেলাফত ব্যবস্থাকে এখানে পুনরুজ্জীবিত করে দেশকে সত্যিকার অর্থে একটি সার্বজনীন কল্যাণ রাষ্ট্রে পরিণত করা। এ শুধু পার্থিব প্রয়োজনেই নয় বরং আখেরাতের মুক্তির জন্যো অপরিহার্য।

বাংলার জমীনে আল্লাহ্র খেলাফত প্রতিষ্ঠার লক্ষ্যে এ দেশের ইসলামী আন্দোলনের ক্ষেত্রে এক নবতর সমন্বয়ধর্মী ও গণভিত্তিক ঐতিহ্য-চেতনা সমৃদ্ধ আপোষহীন নির্ভেজাল ইসলামী আন্দোলন গড়ে তোলার প্রয়োজনে ১৯৮৯ সালের ৮ই ডিসেম্বর খেলাফত মজলিস আত্মপ্রকাশ করেছে।</p>
                    </div>
                </div>
            </div>
            
            
            <div class="row">
              
              <div class="col-md-6">
               <div class="about-me-text margin-top-50">
               <p>মমানুষ আল্লাহর খলিফা ও বান্দা । খেলাফত ও উবুদিয়্যাতের দায়িত্ব যথাযথভাবে আঞ্জাম দেয়ার উপরই মানুষের দুনিয়ার সামগ্রিক কল্যাণ এবং আখেরাতের মুক্তি ও শান্তি নির্ভরশীল। 

ইসলাম মানুষের জন্য মনোনীত দ্বীন ও সর্বোত্তম জীবন ব্যবস্থা। ইবলিসী চক্রান্তে সৃষ্ট শোষণ-নির্যাতন, নৈরাজ্য, অনৈক্য-বিভেদ, অন্যায়-অবিচার-অনাচার, যুদ্ধ-সংঘাতে পরিপূর্ণ বিপর্যস্ত পৃথিবীর হতাশাগ্রস্ত মানুষের একমাত্র মুক্তির পথ ইসলাম। সমাজের সর্বস্তরে ইসলামের পূর্ণ প্রতিষ্ঠাই শান্তি ও অগ্রগতি, সুবিচার ও সাম্যের নিশ্চয়তা দিতে পারে। 

বর্তমানে উলামা মাশায়েখ ও দ্বীনদার শ্রেণীর মাধ্যমে ইসলামের বিভিন্ন পরিমন্ডলে ইসলামের বাস্তবরূপ তথা খেলাফত ব্যবস্থা কায়েম নেই দীর্ঘদিন ধরে। অথচ মানবতার বিশেষভাবে মুসলিম বিশ্বের মুক্তি, সমৃদ্ধি, সম্মান ও দায়িত্ব গোটা মুসলিম জাতির, বিশেষভাবে উলামা-মাশায়েখ, দ্বীনদার বুদ্ধিজীবী ও রাজনীতিকদের।

বাংলাদেশের ক্ষেত্রে এ সত্য সমভাবে প্রযোজ্য। এখানকার সামাজিক বৈষম্য, অর্থনৈতিক শোষণ, রাজনৈতিক নিপীড়ন, হানাহানি, সাংস্কৃতিক নৈরাজ্য ও দেউলিয়াপনা এবং বৈদেশিক আধিপত্যের অবসানে গোটা সমাজ ব্যবস্থাকে ইসলামের আলোকে পুনর্গঠিত করতে হবে। দেশের পনের কোটি মানুষের কল্যাণ ও সমৃদ্ধির জন্য ইসলামী আদর্শের ভিত্তিতে সমাজের বিপ্লবাত্মক পরিবর্তন তথা একটি ইসলামী বিপ্লব প্রয়োজন। প্রয়োন খেলাফত ব্যবস্থাকে এখানে পুনরুজ্জীবিত করে দেশকে সত্যিকার অর্থে একটি সার্বজনীন কল্যাণ রাষ্ট্রে পরিণত করা। এ শুধু পার্থিব প্রয়োজনেই নয় বরং আখেরাতের মুক্তির জন্যো অপরিহার্য।

বাংলার জমীনে আল্লাহ্র খেলাফত প্রতিষ্ঠার লক্ষ্যে এ দেশের ইসলামী আন্দোলনের ক্ষেত্রে এক নবতর সমন্বয়ধর্মী ও গণভিত্তিক ঐতিহ্য-চেতনা সমৃদ্ধ আপোষহীন নির্ভেজাল ইসলামী আন্দোলন গড়ে তোলার প্রয়োজনে ১৯৮৯ সালের ৮ই ডিসেম্বর খেলাফত মজলিস আত্মপ্রকাশ করেছে।</p>
               </div>
              </div>
               
             <div class="col-md-6">
                <div class="about-me-text pattern-bg margin-top-50 margin-bottom-50">
                  <div class="text-center">
                    <a class="button button-style button-style-dark button-style-color-2" data-toggle="modal" data-target="#subscribemodal" href="#">Subscribe</a>
                  </div>
               </div>
               
             <div class="about-me-text">
               
               <ul class="social-icon">
                <li><a href="#" target="_blank" class="facebook"><i class="icon-social-facebook"></i></a></li>
                 <li><a href="#" target="_blank" class="twitter"><i class="icon-social-twitter"></i></a></li>
                 <li><a href="#" target="_blank" class="youtube"><i class="icon-social-youtube"></i></a></li>
               </ul>
               
               </div>
              </div>
              
            </div>
          </div>
       </section>
       
      <!-- Skills Modal Start -->
      <div class="modal fade padding-top-70" id="skillmodal" role="dialog">
        <div class="modal-dialog">
    
      
      <div class="modal-content pattern-bg">
        <div class="modal-body">
           <div class="row">
                <div class="col-sm-12">
                    <div class="section-title margin-top-30">
                      <button type="button" class="btn pull-right" data-dismiss="modal"><i class="fa fa-close"></i></button>
                        <h2>My Skills.</h2>
                         <div class="divider dark">
						   <i class="icon-energy"></i>
						  </div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
                    </div>
                </div>
            </div>
            
          <div class="row">
           <div class="col-sm-offset-2 col-xs-offset-0 col-md-8 col-sm-8">
          
            <div class="my-skill margin-bottom-50">
                    <strong>Graphic Design</strong>
                       <span class="pull-right">80%</span>
                            <div class="progress">
                                 <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 80%;">
                                </div>
                              </div>

                     <strong>Website Design</strong>
                         <span class="pull-right">99%</span>
                             <div class="progress">
                                  <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="99" aria-valuemin="0" aria-valuemax="100" style="width: 99%;">
                                </div>
                              </div>

                      <strong>HTML5/CSS3</strong>
                         <span class="pull-right">85%</span>
                             <div class="progress">
                                  <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 85%;">
                              </div>
                           </div>
                          
                       <strong>Javascript</strong>
                         <span class="pull-right">90%</span>
                             <div class="progress">
                                  <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%;">
                              </div>
                           </div>
                        </div>
          
                   </div>
               </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Skills Modal End -->
      
      
      
      <!-- Subscribe Modal Start -->
      <div class="modal fade subscribe padding-top-120" id="subscribemodal" role="dialog">
        <div class="modal-dialog">
    
      
      <div class="modal-content">
        <div class="modal-body">
           <div class="row">
                <div class="col-sm-12">
                    <div class="section-title margin-top-30">
                      <button type="button" class="btn pull-right" data-dismiss="modal"><i class="fa fa-close"></i></button>
                        <h2>Subscribe.</h2>
                         <div class="divider dark">
						   <i class="icon-envelope-letter"></i>
						  </div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
                    </div>
                </div>
            </div>
            
          <div class="row">
           <div class="col-sm-offset-2 col-xs-offset-0 col-md-8 col-sm-8">
          
            <div class="margin-bottom-50">
                    <form id="mc-form" method="post" action="http://uipasta.us14.list-manage.com/subscribe/post?u=854825d502cdc101233c08a21&amp;id=86e84d44b7">
								
						  <div class="subscribe-form">
							 <input id="mc-email" type="email" placeholder="Email Address" class="text-input">
							  <button class="submit-btn" type="submit">Submit</button>
								</div>
								<label for="mc-email" class="mc-label"></label>
							  </form>
                           </div>
                        </div>
                     </div>
                 </div>
             </div>
          </div>
       </div>
       <!-- Subscribe Modal End -->
       <!-- About End -->
    

    
    <!-- Portfolio Start -->
    <section id="portfolio" class="portfolio section-space-padding">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="section-title">
                        <h2>My Portfolio.</h2>
                          <div class="divider dark">
						   <i class="icon-picture"></i>
						   </div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
                    </div>
                </div>
            </div>
            
            <div class="row">
              <div class="col-md-2">
                <ul class="portfolio">
                    <li class="filter" data-filter="all">all</li>
                    <li class="filter" data-filter=".apps">apps</li>
                    <li class="filter" data-filter=".mockups">mockups</li>
                    <li class="filter" data-filter=".wordpress">wordpress</li>
                </ul>
              </div>
            
            <div class="col-md-10">
                <div class="portfolio-inner margin-top-30">
                
                
                    <div class="col-md-4 col-sm-6 col-xs-12 mix apps">
                        <div class="item">
                            <a href="images/portfolio/1.jpg" class="portfolio-popup" title="Project Title">
                                <img src="images/portfolio/1.jpg" alt="">
                            </a>
                        </div>
                    </div>
                    
                    <div class="col-md-4 col-sm-6 col-xs-12 mix mockups">
                        <div class="item">
                            <a href="images/portfolio/2.jpg" class="portfolio-popup" title="Project Title">
                                <img src="images/portfolio/2.jpg" alt="">
                            </a>
                        </div>
                    </div>
                    
                    <div class="col-md-4 col-sm-6 col-xs-12 mix apps">
                        <div class="item">
                            <a href="images/portfolio/3.jpg" class="portfolio-popup" title="Project Title">
                                <img src="images/portfolio/3.jpg" alt="">
                            </a>
                        </div>
                    </div>
                    
                    <div class="col-md-4 col-sm-6 col-xs-12 mix mockups wordpress">
                        <div class="item">
                            <a href="images/portfolio/4.jpg" class="portfolio-popup" title="Project Title">
                                <img src="images/portfolio/4.jpg" alt="">
                            </a>
                        </div>
                    </div>
                    
                    <div class="col-md-4 col-sm-6 col-xs-12 mix wordpress apps">
                        <div class="item">
                            <a href="images/portfolio/5.jpg" class="portfolio-popup" title="Project Title">
                                <img src="images/portfolio/5.jpg" alt="">
                            </a>
                        </div>
                    </div>
                    
                    <div class="col-md-4 col-sm-6 col-xs-12 mix apps mockups wordpress" title="Project Title">
                        <div class="item">
                            <a href="images/portfolio/6.jpg" class="portfolio-popup">
                                <img src="images/portfolio/6.jpg" alt="">
                            </a>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
       </div>
        
        <div class="text-center margin-top-50">
          <a class="button button-style button-style-dark button-style-color-2 smoth-scroll" href="#contact">Hire Me!</a>
          </div>
     
    </section>
    <!-- Portfolio End -->
    
    
    
     <!-- Testimonial Start -->
     <section id="testimonials" class="testimonial-section section-space-padding">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="section-title">
                        <h2>Videos.</h2>
                         <div class="divider dark">
						   <i class="icon-speech"></i>
						  </div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                    </div>
                </div>
            </div>
            
            <div class="row">
              <div class="col-md-offset-3 col-sm-offset-2 col-md-6 col-sm-8">
                <div class="testimonial-carousel-list margin-top-20">
                
                    <div class="testimonial-word text-center">
						<iframe width="100%" height="100%" src="https://www.youtube.com/embed/DSQtqpW_Dws" frameborder="0" allowfullscreen></iframe>
                    </div>
                    
                    <div class="testimonial-word text-center">
                        <iframe width="100%" height="100%" src="https://www.youtube.com/embed/5G8E5DkEu30" frameborder="0" allowfullscreen></iframe>
                    </div>
                    
                    <div class="testimonial-word text-center">
                        <iframe width="100%" height="100%" src="https://www.youtube.com/embed/fShM5UsNruc" frameborder="0" allowfullscreen></iframe>
                    </div>
                    
                </div>
              </div>
             
            </div>
        </div>
    </section>
    <!-- Testimonial End -->
    
    
    
      <!-- statistics -->
      <section class="statistics-section section-space-padding bg-cover text-center">
         <div class="container">     

            <div class="row">

           <div class="col-md-3 col-sm-6 col-xs-6">
            <div class="statistics bg-color-1">
              <div class="statistics-icon"><i class="icon-mustache"></i>
              </div>
              <div class="statistics-content">
                <h5><span data-count="2025" class="statistics-count">2025</span></h5><span>Projects Done</span>
              </div>
            </div>
          </div>
          
          <div class="col-md-3 col-sm-6 col-xs-6">
            <div class="statistics bg-color-6">
              <div class="statistics-icon"><i class="icon-emotsmile"></i>
              </div>
              <div class="statistics-content">
                <h5> <span data-count="1200" class="statistics-count">1200</span></h5><span>Happy Clients</span>
              </div>
            </div>
          </div>
          
          <div class="col-md-3 col-sm-6 col-xs-6">
            <div class="statistics bg-color-4">
              <div class="statistics-icon"><i class="icon-hourglass"></i>
              </div>
              <div class="statistics-content">
                <h5><span data-count="8000" class="statistics-count">8000</span></h5><span>Hours of Work</span>
              </div>
            </div>
          </div>
          
          <div class="col-md-3 col-sm-6 col-xs-6">
            <div class="statistics bg-color-5">
              <div class="statistics-icon"><i class="icon-cup"></i>
              </div>
              <div class="statistics-content">
                <h5><span data-count="4000" class="statistics-count">4000</span></h5><span>Cup of Coffee</span>
              </div>
            </div>
            </div>

         </div>
       </div>
    </section>
    <!-- statistics end -->

    
    
    
    <!-- Services Start -->
    <section id="services" class="services-section section-space-padding">
        <div class="container">
           <div class="row">
                <div class="col-sm-12">
                    <div class="section-title">
                        <h2>My Services.</h2>
                          <div class="divider dark">
						   <i class="icon-drop"></i>
						 </div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
                    </div>
                </div>
            </div>
            
            <div class="row margin-top-30 text-center">
                <div class="col-md-6 col-sm-6">
                    <img class='services-detail' src='images/etc/people/mawlana_muhammad_ishaq-khelafat_majlish.jpg'></i>
                </div>

                <div class="col-md-6 col-sm-6">
                    <img class='services-detail' src='images/etc/people/ahmed_abdul_kader-khelafat_majlish.png'></i>
                </div>
            </div>
            
            <div class="row margin-top-30 text-center">
                <div class="col-md-4 col-sm-6">
                    <div class="services-detail">
                        <i class="icon-support color-4"></i>
                        <h3>Full Support</h3>
                        <hr>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6">
                    <div class="services-detail">
                        <i class="fa fa-html5 color-5"></i>
                        <h3>HTML5 Design</h3>
                        <hr>
                    </div>
                </div>

                <div class="col-md-4 col-sm-6">
                    <div class="services-detail">
                        <i class="icon-bulb color-6"></i>
                        <h3>CSS3 Design</h3>
                        <hr>
                    </div>
                </div>
            
            </div>
        </div>
    </section>
    <!-- Services End -->
    
    
    
    <!-- Call to Action Start -->
    <section class="call-to-action bg-cover section-space-padding text-center">
       <div class="container">
         <div class="row">
           <div class="col-md-8">
             <h2>Do You Want to Know More About Me?</h2>
             </div>
             
            <div class="col-md-4">
             <div class="text-center">
               <a class="button button-style button-style-color-2 smoth-scroll" href="#contact">Contact Me</a>
            </div>
            
            </div>    
          </div>
         </div>
       </section>
       <!-- Call to Action End -->
       
       
       
       
    <!-- Contact Start -->
    <section id="contact" class="section-space-padding">
       <div class="container">
          <div class="row">
                <div class="col-sm-12">
                    <div class="section-title">
                        <h2>যোগাযোগ</h2>
                          <div class="divider dark">
						   <i class="icon-envelope-open"></i>
						 </div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
                    </div>
                </div>
            </div>
            
         
         <div class="margin-top-30 margin-bottom-50">
           <div class="row">
           
             <div class="col-md-offset-3 col-sm-offset-2 col-md-6 col-sm-8">   
                 
               <div class="row">
                 <div class="contact-us-detail"><a href="mailto:name@domain.com">name@domain.com</a></div>
                  <form class="contact-us pattern-bg">
                    
					  <div class="col-sm-6">
						<div class="form-group">
						  <input type="text" id="name" class="form-control" placeholder="Your Name">
						 </div>
                        </div>
								
                       <div class="col-sm-6">
					    <div class="form-group">
						 <input type="email" id="email" class="form-control" placeholder="Your Email">
						 </div>
                        </div>
                        
                        <div class="col-sm-6">
						  <div class="form-group">
							<input type="text" id="website" class="form-control" placeholder="Your Website">
						   </div>
                          </div>
                          
                        <div class="col-sm-6">
						  <div class="form-group">
							<input type="text" id="address" class="form-control" placeholder="Where are You From?">
						   </div>
                          </div>
								
                         <div class="col-sm-12">
						  <select id="subject" class="form-group form-control">
							<option value="" selected disabled>Subject</option>
							<option>Website Design & Development</option>
							<option>Wordpress Development</option>
							<option>Search Engine Optimization</option>
                            <option>Mobile Website</option>
							<option>I Want to General Talk</option>
                            <option>Other</option>
						   </select>
                          </div>
								
                       <div class="col-sm-12">
					    <div class="textarea-message form-group">
					      <textarea id="message" class="textarea-message form-control" placeholder="Your Message" rows="5"></textarea>
						  </div>
                         </div>
                   
                   
                    <div class="text-center">      
		               <button type="submit" class="button button-style button-style-dark button-style-color-2">Submit</button>
	                  </div>
                       
                  </form>
                   
                </div>
			  </div>
            </div>
           
        
        </div>
       </div>
     </section>
     <!-- Contact End -->
       
        